"""update

Revision ID: 0cbf27ab9c2a
Revises: 
Create Date: 2020-11-09 20:16:20.496708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbf27ab9c2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport',
    sa.Column('icao', sa.String(), nullable=False),
    sa.Column('tk', sa.Integer(), nullable=True),
    sa.Column('ld', sa.Integer(), nullable=True),
    sa.Column('tx', sa.Integer(), nullable=True),
    sa.Column('rw', sa.Integer(), nullable=True),
    sa.Column('ps', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('icao')
    )
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('pilot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aircraft',
    sa.Column('call_sign', sa.String(), nullable=False),
    sa.Column('model_no', sa.String(), nullable=True),
    sa.Column('turn_around_count', sa.Integer(), nullable=True),
    sa.Column('sc', sa.String(), nullable=True),
    sa.Column('ds', sa.String(), nullable=True),
    sa.Column('emergency', sa.Boolean(), nullable=True),
    sa.Column('altitude', sa.Integer(), nullable=True),
    sa.Column('pilot', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.Column('crash', sa.Boolean(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.id'], ),
    sa.ForeignKeyConstraint(['pilot'], ['pilots.id'], ),
    sa.PrimaryKeyConstraint('call_sign')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aircraft')
    op.drop_table('company')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('pilots')
    op.drop_table('airport')
    # ### end Alembic commands ###
